[package]
name = "solana-secp256r1-program"
description = "Precompile implementation for the secp256r1 elliptic curve."
documentation = "https://docs.rs/solana-secp256r1"
version = "2.2.4"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
default = []
openssl-vendored = ["openssl/vendored"]

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
solana-sdk-ids = { workspace = true }

[target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "solana")))'.dependencies]
openssl = { workspace = true }
solana-instruction = { workspace = true, features = ["std"] }

[lints]
workspace = true
