[package]
name = "solana-sanitize"
description = "Solana Message Sanitization"
documentation = "https://docs.rs/solana-sanitize"
rust-version = "1.81.0"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
