[package]
name = "solana-message"
description = "Solana transaction message types."
documentation = "https://docs.rs/solana-message"
version = "3.0.1"
rust-version = "1.81.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = ["dep:bincode", "serde"]
blake3 = ["dep:blake3"]
dev-context-only-utils = ["bincode", "blake3"]
frozen-abi = [
    "dep:solana-frozen-abi",
    "dep:solana-frozen-abi-macro",
    "dep:solana-logger",
    "solana-address/frozen-abi",
    "solana-hash/frozen-abi",
    "serde",
]
serde = [
    "dep:serde",
    "dep:serde_derive",
    "dep:solana-short-vec",
    "serde/alloc",
    "solana-address/serde",
    "solana-hash/serde",
]

[dependencies]
bincode = { workspace = true, optional = true }
blake3 = { workspace = true, features = ["traits-preview"], optional = true }
lazy_static = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-address = { workspace = true }
solana-frozen-abi = { workspace = true, optional = true }
solana-frozen-abi-macro = { workspace = true, optional = true }
solana-hash = { workspace = true }
solana-instruction = { workspace = true, features = ["std"] }
solana-logger = { workspace = true, optional = true }
solana-sanitize = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-short-vec = { workspace = true, optional = true }
solana-transaction-error = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
bitflags = { workspace = true }
borsh = { workspace = true }
itertools = { workspace = true }
serde_json = { workspace = true }
solana-address-lookup-table-interface = { workspace = true, features = [
    "bincode",
    "bytemuck",
] }
solana-example-mocks = { path = "../example-mocks" }
solana-instruction = { workspace = true, features = ["borsh"] }
solana-instruction-error = { workspace = true }
solana-message = { path = ".", features = ["dev-context-only-utils"] }
solana-nonce = { workspace = true }
solana-system-interface = { workspace = true, features = ["bincode"] }
static_assertions = { workspace = true }

[lints]
workspace = true
