[package]
name = "solana-secp256k1-program"
description = "Instructions for the Solana Secp256k1 native program."
documentation = "https://docs.rs/solana-secp256k1-program"
version = "2.2.3"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = [
    "dep:bincode",
    "dep:solana-instruction",
    "dep:solana-sdk-ids",
    "serde",
]
dev-context-only-utils = ["bincode"]
serde = ["dep:serde", "dep:serde_derive"]

[dependencies]
bincode = { workspace = true, optional = true }
digest = { workspace = true }
libsecp256k1 = { workspace = true, features = ["hmac"] }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
sha3 = { workspace = true }
solana-instruction = { workspace = true, features = ["std"], optional = true }
solana-sdk-ids = { workspace = true, optional = true }
solana-signature = { workspace = true, features = ["std"] }

[dev-dependencies]
anyhow = { workspace = true }
hex = { workspace = true }
rand0-7 = { workspace = true }
solana-account-info = { workspace = true }
solana-example-mocks = { path = "../example-mocks" }
solana-instruction = { workspace = true }
solana-instructions-sysvar = { workspace = true }
solana-keccak-hasher = { workspace = true }
solana-msg = { workspace = true }
solana-program-error = { workspace = true }
solana-secp256k1-program = { path = ".", features = ["bincode"] }
