[package]
name = "solana-transaction"
description = "Solana transaction-types"
documentation = "https://docs.rs/solana-transaction"
version = "3.0.2"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = [
    "dep:bincode",
    "dep:solana-signer",
    "serde",
    "solana-message/bincode",
]
blake3 = ["bincode", "solana-message/blake3"]
dev-context-only-utils = ["blake3", "serde", "verify", "solana-hash/atomic"]
frozen-abi = [
    "dep:solana-frozen-abi",
    "dep:solana-frozen-abi-macro",
    "solana-transaction-error/frozen-abi",
]
serde = [
    "dep:serde",
    "dep:serde_derive",
    "dep:solana-short-vec",
    "solana-message/serde",
    "solana-signature/serde",
    "solana-transaction-error/serde",
]
verify = ["blake3", "solana-signature/verify"]

[dependencies]
bincode = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-address = { workspace = true }
solana-frozen-abi = { workspace = true, optional = true }
solana-frozen-abi-macro = { workspace = true, optional = true }
solana-hash = { workspace = true }
solana-instruction = { workspace = true }
solana-instruction-error = { workspace = true }
solana-message = { workspace = true }
solana-sanitize = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-short-vec = { workspace = true, optional = true }
solana-signature = { workspace = true }
solana-signer = { workspace = true, optional = true }
solana-transaction-error = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
solana-example-mocks = { path = "../example-mocks" }
solana-hash = { workspace = true, features = ["atomic"] }
solana-instruction = { workspace = true, features = ["borsh"] }
solana-keypair = { workspace = true }
solana-nonce = { workspace = true }
solana-packet = { workspace = true }
solana-presigner = { workspace = true }
solana-pubkey = { workspace = true, features = ["rand"] }
solana-sha256-hasher = { workspace = true }
solana-system-interface = { workspace = true, features = ["bincode"] }
solana-transaction = { path = ".", features = ["dev-context-only-utils"] }
solana-vote-interface = { workspace = true, features = ["bincode"] }
static_assertions = { workspace = true }
